### ISSUE TITLE
🐛Site breaks after a while, during sales.

### ISSUE THREAD

**Issue by kuhnfelix18052005** [HiEventsDev/Hi.Events#177]
**Describe the bug**
Essentially I created an event with tiered tickets and non tiered tickets. Everything works perfectly but after a while the Tickets page on the backend does not load anymore and the front just says something went wrong. The error message pulled from the digitalocean runtime log is below. I do not know where to find more detailed logs about this issue, but so far I have not been able to pinpoint the cause of the bug as it seems pretty random.

I have previously succeeded in fixing this bug by accessing the database and changing some value back and forth, however after it broke again, changing the same stuff had no effect so there is the possibility that it is not associated with that. 

**Expected behavior**
It was expected to work or at least indicate what is wrong.

**Hi.Events Version and platform**
Newest version at moment of publishing this issue, deployed on digitalocean. 

**Logs**
[logs.txt](https://github.com/user-attachments/files/16826251/logs.txt)

**Additional context**
This is a very important issue, as I generally really support this platform and would like to use it extensively, however if I am not able to pinpoint and fix the origin of this bug I will not be able to.

As the developer of this platform, what should the next locations be that I should look for the origins of this issue so that it can be fixed hopefully in the near future?

**Comment by daveearley** [comment]
Hi @kuhnfelix18052005, Sorry you're experiencing issues.

Could you add a new environment variable in DigitalOcean: `APP_DEBUG=true`. Then try to load the failing page again. This should result in more logs being output.

> I have previously succeeded in fixing this bug by accessing the database and changing some value back and forth, however after it broke again, changing the same stuff had no effect so there is the possibility that it is not associated with that.

Could you elaborate on this please. What values did you have to change, and what was breaking?

Also, did you deploy using the "Deploy with DigitalOcean" button, or did you deploy the images yourself?

Thanks.

**Comment by kuhnfelix18052005** [comment]
Hi @daveearley, thank you for responding so quickly,

The variables I changed were mostly changing tickets from visible to hidden which mostly had no effect but then at some point I just set the total amount sold in euros to zero and upon refreshing the page it did work again. But then some people continued buying tickets which caused it to break again. 

I added APP_DEBUG=true, so far nowhere else there are more logs that I can see so I just added the runtime log of that request again. 

```
#54 {main}
[hi-events] [2024-08-31 22:17:32] "} 
[hi-events] [2024-08-31 22:17:32] ::1 - - [31/Aug/2024:22:17:32 +0000] "GET /api/public/events/2 HTTP/1.1" 500 15368 "-" "axios/1.7.5"
[hi-events] [2024-08-31 22:17:32] 127.0.0.1 -  31/Aug/2024:22:17:32 +0000 "GET /index.php/public/events/2" 500
[hi-events] [2024-08-31 22:17:32] AxiosError: Request failed with status code 500
[hi-events] [2024-08-31 22:17:32]     at settle (file:///app/frontend/node_modules/axios/lib/core/settle.js:19:12)
[hi-events] [2024-08-31 22:17:32]     at IncomingMessage.handleStreamEnd (file:///app/frontend/node_modules/axios/lib/adapters/http.js:599:11)
[hi-events] [2024-08-31 22:17:32]     at IncomingMessage.emit (node:events:531:35)
[hi-events] [2024-08-31 22:17:32]     at endReadableNT (node:internal/streams/readable:1696:12)
[hi-events] [2024-08-31 22:17:32]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[hi-events] [2024-08-31 22:17:32]     at Axios.request (file:///app/frontend/node_modules/axios/lib/core/Axios.js:45:41)
[hi-events] [2024-08-31 22:17:32]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[hi-events] [2024-08-31 22:17:32]     at async Object.findByID (file:///app/frontend/dist/server/entry.server.js:349:22)
[hi-events] [2024-08-31 22:17:32]     at async loader (file:///app/frontend/dist/server/entry.server.js:797:11)
[hi-events] [2024-08-31 22:17:32]     at async /app/frontend/node_modules/@remix-run/router/dist/router.cjs.js:4674:21
[hi-events] [2024-08-31 22:17:32]     at async Promise.all (index 0)
[hi-events] [2024-08-31 22:17:32]     at async callLoaderOrAction (/app/frontend/node_modules/@remix-run/router/dist/router.cjs.js:4695:23)
[hi-events] [2024-08-31 22:17:32]     at async Promise.all (index 0)
[hi-events] [2024-08-31 22:17:32]     at async callDataStrategyImpl (/app/frontend/node_modules/@remix-run/router/dist/router.cjs.js:4614:17)
[hi-events] [2024-08-31 22:17:32]     at async callDataStrategy (/app/frontend/node_modules/@remix-run/router/dist/router.cjs.js:4102:19) {
[hi-events] [2024-08-31 22:17:32]   code: 'ERR_BAD_RESPONSE',
[hi-events] [2024-08-31 22:17:32]   config: {
[hi-events] [2024-08-31 22:17:32]     transitional: {
[hi-events] [2024-08-31 22:17:32]       silentJSONParsing: true,
[hi-events] [2024-08-31 22:17:32]       forcedJSONParsing: true,
[hi-events] [2024-08-31 22:17:32]       clarifyTimeoutError: false
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     adapter: [ 'xhr', 'http', 'fetch' ],
[hi-events] [2024-08-31 22:17:32]     transformRequest: [ [Function: transformRequest] ],
[hi-events] [2024-08-31 22:17:32]     transformResponse: [ [Function: transformResponse] ],
[hi-events] [2024-08-31 22:17:32]     timeout: 0,
[hi-events] [2024-08-31 22:17:32]     xsrfCookieName: 'XSRF-TOKEN',
[hi-events] [2024-08-31 22:17:32]     xsrfHeaderName: 'X-XSRF-TOKEN',
[hi-events] [2024-08-31 22:17:32]     maxContentLength: -1,
[hi-events] [2024-08-31 22:17:32]     maxBodyLength: -1,
[hi-events] [2024-08-31 22:17:32]     env: { FormData: [Function], Blob: [class Blob] },
[hi-events] [2024-08-31 22:17:32]     validateStatus: [Function: validateStatus],
[hi-events] [2024-08-31 22:17:32]     headers: Object [AxiosHeaders] {
[hi-events] [2024-08-31 22:17:32]       Accept: 'application/json, text/plain, */*',
[hi-events] [2024-08-31 22:17:32]       'Content-Type': undefined,
[hi-events] [2024-08-31 22:17:32]       Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3RpY2tldHMuZWJzLXNvY2lldHkuY29tL2F1dGgvbG9naW4iLCJpYXQiOjE3MjUxNDIxMTAsImV4cCI6MTcyNTc0NjkxMCwibmJmIjoxNzI1MTQyMTEwLCJqdGkiOiJZejlTcmtQY3gyR0cya1U3Iiwic3ViIjoiMSIsInBydiI6ImI1YjFhZjFhZWY1MWUyMmU1Y2JlMzk0YzM3NDU3MjJhYjgwYWQ2Y2MiLCJhY2NvdW50X2lkIjoxfQ.ahD1CYuHIh1sH8umow2YbTk04cf5KuxySVKPvdSs0dA',
[hi-events] [2024-08-31 22:17:32]       'User-Agent': 'axios/1.7.5',
[hi-events] [2024-08-31 22:17:32]       'Accept-Encoding': 'gzip, compress, deflate, br'
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     method: 'get',
[hi-events] [2024-08-31 22:17:32]     url: 'events/2',
[hi-events] [2024-08-31 22:17:32]     baseURL: 'http://localhost:80/api/public',
[hi-events] [2024-08-31 22:17:32]     data: undefined
[hi-events] [2024-08-31 22:17:32]   },
[hi-events] [2024-08-31 22:17:32]   request: <ref *1> ClientRequest {
[hi-events] [2024-08-31 22:17:32]     _events: [Object: null prototype] {
[hi-events] [2024-08-31 22:17:32]       abort: [Function (anonymous)],
[hi-events] [2024-08-31 22:17:32]       aborted: [Function (anonymous)],
[hi-events] [2024-08-31 22:17:32]       connect: [Function (anonymous)],
[hi-events] [2024-08-31 22:17:32]       error: [Function (anonymous)],
[hi-events] [2024-08-31 22:17:32]       socket: [Function (anonymous)],
[hi-events] [2024-08-31 22:17:32]       timeout: [Function (anonymous)],
[hi-events] [2024-08-31 22:17:32]       finish: [Function: requestOnFinish]
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     _eventsCount: 7,
[hi-events] [2024-08-31 22:17:32]     _maxListeners: undefined,
[hi-events] [2024-08-31 22:17:32]     outputData: [],
[hi-events] [2024-08-31 22:17:32]     outputSize: 0,
[hi-events] [2024-08-31 22:17:32]     writable: true,
[hi-events] [2024-08-31 22:17:32]     destroyed: true,
[hi-events] [2024-08-31 22:17:32]     _last: true,
[hi-events] [2024-08-31 22:17:32]     chunkedEncoding: false,
[hi-events] [2024-08-31 22:17:32]     shouldKeepAlive: true,
[hi-events] [2024-08-31 22:17:32]     maxRequestsOnConnectionReached: false,
[hi-events] [2024-08-31 22:17:32]     _defaultKeepAlive: true,
[hi-events] [2024-08-31 22:17:32]     useChunkedEncodingByDefault: false,
[hi-events] [2024-08-31 22:17:32]     sendDate: false,
[hi-events] [2024-08-31 22:17:32]     _removedConnection: false,
[hi-events] [2024-08-31 22:17:32]     _removedContLen: false,
[hi-events] [2024-08-31 22:17:32]     _removedTE: false,
[hi-events] [2024-08-31 22:17:32]     strictContentLength: false,
[hi-events] [2024-08-31 22:17:32]     _contentLength: 0,
[hi-events] [2024-08-31 22:17:32]     _hasBody: true,
[hi-events] [2024-08-31 22:17:32]     _trailer: '',
[hi-events] [2024-08-31 22:17:32]     finished: true,
[hi-events] [2024-08-31 22:17:32]     _headerSent: true,
[hi-events] [2024-08-31 22:17:32]     _closed: true,
[hi-events] [2024-08-31 22:17:32]     socket: Socket {
[hi-events] [2024-08-31 22:17:32]       connecting: false,
[hi-events] [2024-08-31 22:17:32]       _hadError: false,
[hi-events] [2024-08-31 22:17:32]       _parent: null,
[hi-events] [2024-08-31 22:17:32]       _host: 'localhost',
[hi-events] [2024-08-31 22:17:32]       _closeAfterHandlingError: false,
[hi-events] [2024-08-31 22:17:32]       _events: [Object],
[hi-events] [2024-08-31 22:17:32]       _readableState: [ReadableState],
[hi-events] [2024-08-31 22:17:32]       _writableState: [WritableState],
[hi-events] [2024-08-31 22:17:32]       allowHalfOpen: false,
[hi-events] [2024-08-31 22:17:32]       _maxListeners: undefined,
[hi-events] [2024-08-31 22:17:32]       _eventsCount: 6,
[hi-events] [2024-08-31 22:17:32]       _sockname: null,
[hi-events] [2024-08-31 22:17:32]       _pendingData: null,
[hi-events] [2024-08-31 22:17:32]       _pendingEncoding: '',
[hi-events] [2024-08-31 22:17:32]       server: null,
[hi-events] [2024-08-31 22:17:32]       _server: null,
[hi-events] [2024-08-31 22:17:32]       timeout: 5000,
[hi-events] [2024-08-31 22:17:32]       parser: null,
[hi-events] [2024-08-31 22:17:32]       _httpMessage: null,
[hi-events] [2024-08-31 22:17:32]       autoSelectFamilyAttemptedAddresses: [Array],
[hi-events] [2024-08-31 22:17:32]       [Symbol(async_id_symbol)]: -1,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kHandle)]: [TCP],
[hi-events] [2024-08-31 22:17:32]       [Symbol(lastWriteQueueSize)]: 0,
[hi-events] [2024-08-31 22:17:32]       [Symbol(timeout)]: Timeout {
[hi-events] [2024-08-31 22:17:32]         _idleTimeout: 5000,
[hi-events] [2024-08-31 22:17:32]         _idlePrev: [TimersList],
[hi-events] [2024-08-31 22:17:32]         _idleNext: [TimersList],
[hi-events] [2024-08-31 22:17:32]         _idleStart: 93775,
[hi-events] [2024-08-31 22:17:32]         _onTimeout: [Function: bound ],
[hi-events] [2024-08-31 22:17:32]         _timerArgs: undefined,
[hi-events] [2024-08-31 22:17:32]         _repeat: null,
[hi-events] [2024-08-31 22:17:32]         _destroyed: false,
[hi-events] [2024-08-31 22:17:32]         [Symbol(refed)]: false,
[hi-events] [2024-08-31 22:17:32]         [Symbol(kHasPrimitive)]: false,
[hi-events] [2024-08-31 22:17:32]         [Symbol(asyncId)]: 5769,
[hi-events] [2024-08-31 22:17:32]         [Symbol(triggerId)]: 5767
[hi-events] [2024-08-31 22:17:32]       },
[hi-events] [2024-08-31 22:17:32]       [Symbol(kBuffer)]: null,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kBufferCb)]: null,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kBufferGen)]: null,
[hi-events] [2024-08-31 22:17:32]       [Symbol(shapeMode)]: true,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kCapture)]: false,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kSetNoDelay)]: true,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kSetKeepAlive)]: true,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kSetKeepAliveInitialDelay)]: 1,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kBytesRead)]: 0,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kBytesWritten)]: 0
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     _header: 'GET /api/public/events/2 HTTP/1.1\r\n' +
[hi-events] [2024-08-31 22:17:32]       'Accept: application/json, text/plain, */*\r\n' +
[hi-events] [2024-08-31 22:17:32]       'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3RpY2tldHMuZWJzLXNvY2lldHkuY29tL2F1dGgvbG9naW4iLCJpYXQiOjE3MjUxNDIxMTAsImV4cCI6MTcyNTc0NjkxMCwibmJmIjoxNzI1MTQyMTEwLCJqdGkiOiJZejlTcmtQY3gyR0cya1U3Iiwic3ViIjoiMSIsInBydiI6ImI1YjFhZjFhZWY1MWUyMmU1Y2JlMzk0YzM3NDU3MjJhYjgwYWQ2Y2MiLCJhY2NvdW50X2lkIjoxfQ.ahD1CYuHIh1sH8umow2YbTk04cf5KuxySVKPvdSs0dA\r\n' +
[hi-events] [2024-08-31 22:17:32]       'User-Agent: axios/1.7.5\r\n' +
[hi-events] [2024-08-31 22:17:32]       'Accept-Encoding: gzip, compress, deflate, br\r\n' +
[hi-events] [2024-08-31 22:17:32]       'Host: localhost\r\n' +
[hi-events] [2024-08-31 22:17:32]       'Connection: keep-alive\r\n' +
[hi-events] [2024-08-31 22:17:32]       '\r\n',
[hi-events] [2024-08-31 22:17:32]     _keepAliveTimeout: 0,
[hi-events] [2024-08-31 22:17:32]     _onPendingData: [Function: nop],
[hi-events] [2024-08-31 22:17:32]     agent: Agent {
[hi-events] [2024-08-31 22:17:32]       _events: [Object: null prototype],
[hi-events] [2024-08-31 22:17:32]       _eventsCount: 2,
[hi-events] [2024-08-31 22:17:32]       _maxListeners: undefined,
[hi-events] [2024-08-31 22:17:32]       defaultPort: 80,
[hi-events] [2024-08-31 22:17:32]       protocol: 'http:',
[hi-events] [2024-08-31 22:17:32]       options: [Object: null prototype],
[hi-events] [2024-08-31 22:17:32]       requests: [Object: null prototype] {},
[hi-events] [2024-08-31 22:17:32]       sockets: [Object: null prototype] {},
[hi-events] [2024-08-31 22:17:32]       freeSockets: [Object: null prototype],
[hi-events] [2024-08-31 22:17:32]       keepAliveMsecs: 1000,
[hi-events] [2024-08-31 22:17:32]       keepAlive: true,
[hi-events] [2024-08-31 22:17:32]       maxSockets: Infinity,
[hi-events] [2024-08-31 22:17:32]       maxFreeSockets: 256,
[hi-events] [2024-08-31 22:17:32]       scheduling: 'lifo',
[hi-events] [2024-08-31 22:17:32]       maxTotalSockets: Infinity,
[hi-events] [2024-08-31 22:17:32]       totalSocketCount: 1,
[hi-events] [2024-08-31 22:17:32]       [Symbol(shapeMode)]: false,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kCapture)]: false
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     socketPath: undefined,
[hi-events] [2024-08-31 22:17:32]     method: 'GET',
[hi-events] [2024-08-31 22:17:32]     maxHeaderSize: undefined,
[hi-events] [2024-08-31 22:17:32]     insecureHTTPParser: undefined,
[hi-events] [2024-08-31 22:17:32]     joinDuplicateHeaders: undefined,
[hi-events] [2024-08-31 22:17:32]     path: '/api/public/events/2',
[hi-events] [2024-08-31 22:17:32]     _ended: true,
[hi-events] [2024-08-31 22:17:32]     res: IncomingMessage {
[hi-events] [2024-08-31 22:17:32]       _events: [Object],
[hi-events] [2024-08-31 22:17:32]       _readableState: [ReadableState],
[hi-events] [2024-08-31 22:17:32]       _maxListeners: undefined,
[hi-events] [2024-08-31 22:17:32]       socket: null,
[hi-events] [2024-08-31 22:17:32]       httpVersionMajor: 1,
[hi-events] [2024-08-31 22:17:32]       httpVersionMinor: 1,
[hi-events] [2024-08-31 22:17:32]       httpVersion: '1.1',
[hi-events] [2024-08-31 22:17:32]       complete: true,
[hi-events] [2024-08-31 22:17:32]       rawHeaders: [Array],
[hi-events] [2024-08-31 22:17:32]       rawTrailers: [],
[hi-events] [2024-08-31 22:17:32]       joinDuplicateHeaders: undefined,
[hi-events] [2024-08-31 22:17:32]       aborted: false,
[hi-events] [2024-08-31 22:17:32]       upgrade: false,
[hi-events] [2024-08-31 22:17:32]       url: '',
[hi-events] [2024-08-31 22:17:32]       method: null,
[hi-events] [2024-08-31 22:17:32]       statusCode: 500,
[hi-events] [2024-08-31 22:17:32]       statusMessage: 'Internal Server Error',
[hi-events] [2024-08-31 22:17:32]       client: [Socket],
[hi-events] [2024-08-31 22:17:32]       _consuming: false,
[hi-events] [2024-08-31 22:17:32]       _dumped: false,
[hi-events] [2024-08-31 22:17:32]       req: [Circular *1],
[hi-events] [2024-08-31 22:17:32]       _eventsCount: 4,
[hi-events] [2024-08-31 22:17:32]       responseUrl: 'http://localhost/api/public/events/2',
[hi-events] [2024-08-31 22:17:32]       redirects: [],
[hi-events] [2024-08-31 22:17:32]       [Symbol(shapeMode)]: true,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kCapture)]: false,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kHeaders)]: [Object],
[hi-events] [2024-08-31 22:17:32]       [Symbol(kHeadersCount)]: 24,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kTrailers)]: null,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kTrailersCount)]: 0
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     aborted: false,
[hi-events] [2024-08-31 22:17:32]     timeoutCb: null,
[hi-events] [2024-08-31 22:17:32]     upgradeOrConnect: false,
[hi-events] [2024-08-31 22:17:32]     parser: null,
[hi-events] [2024-08-31 22:17:32]     maxHeadersCount: null,
[hi-events] [2024-08-31 22:17:32]     reusedSocket: false,
[hi-events] [2024-08-31 22:17:32]     host: 'localhost',
[hi-events] [2024-08-31 22:17:32]     protocol: 'http:',
[hi-events] [2024-08-31 22:17:32]     _redirectable: Writable {
[hi-events] [2024-08-31 22:17:32]       _events: [Object],
[hi-events] [2024-08-31 22:17:32]       _writableState: [WritableState],
[hi-events] [2024-08-31 22:17:32]       _maxListeners: undefined,
[hi-events] [2024-08-31 22:17:32]       _options: [Object],
[hi-events] [2024-08-31 22:17:32]       _ended: true,
[hi-events] [2024-08-31 22:17:32]       _ending: true,
[hi-events] [2024-08-31 22:17:32]       _redirectCount: 0,
[hi-events] [2024-08-31 22:17:32]       _redirects: [],
[hi-events] [2024-08-31 22:17:32]       _requestBodyLength: 0,
[hi-events] [2024-08-31 22:17:32]       _requestBodyBuffers: [],
[hi-events] [2024-08-31 22:17:32]       _eventsCount: 3,
[hi-events] [2024-08-31 22:17:32]       _onNativeResponse: [Function (anonymous)],
[hi-events] [2024-08-31 22:17:32]       _currentRequest: [Circular *1],
[hi-events] [2024-08-31 22:17:32]       _currentUrl: 'http://localhost/api/public/events/2',
[hi-events] [2024-08-31 22:17:32]       [Symbol(shapeMode)]: true,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kCapture)]: false
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     [Symbol(shapeMode)]: false,
[hi-events] [2024-08-31 22:17:32]     [Symbol(kCapture)]: false,
[hi-events] [2024-08-31 22:17:32]     [Symbol(kBytesWritten)]: 0,
[hi-events] [2024-08-31 22:17:32]     [Symbol(kNeedDrain)]: false,
[hi-events] [2024-08-31 22:17:32]     [Symbol(corked)]: 0,
[hi-events] [2024-08-31 22:17:32]     [Symbol(kOutHeaders)]: [Object: null prototype] {
[hi-events] [2024-08-31 22:17:32]       accept: [Array],
[hi-events] [2024-08-31 22:17:32]       authorization: [Array],
[hi-events] [2024-08-31 22:17:32]       'user-agent': [Array],
[hi-events] [2024-08-31 22:17:32]       'accept-encoding': [Array],
[hi-events] [2024-08-31 22:17:32]       host: [Array]
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     [Symbol(errored)]: null,
[hi-events] [2024-08-31 22:17:32]     [Symbol(kHighWaterMark)]: 16384,
[hi-events] [2024-08-31 22:17:32]     [Symbol(kRejectNonStandardBodyWrites)]: false,
[hi-events] [2024-08-31 22:17:32]     [Symbol(kUniqueHeaders)]: null
[hi-events] [2024-08-31 22:17:32]   },
[hi-events] [2024-08-31 22:17:32]   response: {
[hi-events] [2024-08-31 22:17:32]     status: 500,
[hi-events] [2024-08-31 22:17:32]     statusText: 'Internal Server Error',
[hi-events] [2024-08-31 22:17:32]     headers: Object [AxiosHeaders] {
[hi-events] [2024-08-31 22:17:32]       server: 'nginx/1.24.0',
[hi-events] [2024-08-31 22:17:32]       'content-type': 'application/json',
[hi-events] [2024-08-31 22:17:32]       'transfer-encoding': 'chunked',
[hi-events] [2024-08-31 22:17:32]       connection: 'keep-alive',
[hi-events] [2024-08-31 22:17:32]       'x-powered-by': 'PHP/8.3.2',
[hi-events] [2024-08-31 22:17:32]       'cache-control': 'no-cache, private',
[hi-events] [2024-08-31 22:17:32]       date: 'Sat, 31 Aug 2024 22:17:32 GMT',
[hi-events] [2024-08-31 22:17:32]       'x-ratelimit-limit': '120',
[hi-events] [2024-08-31 22:17:32]       'x-ratelimit-remaining': '103',
[hi-events] [2024-08-31 22:17:32]       'access-control-allow-origin': 'https://tickets.ebs-society.com',
[hi-events] [2024-08-31 22:17:32]       'access-control-allow-credentials': 'true',
[hi-events] [2024-08-31 22:17:32]       'access-control-expose-headers': 'X-Auth-Token'
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     config: {
[hi-events] [2024-08-31 22:17:32]       transitional: [Object],
[hi-events] [2024-08-31 22:17:32]       adapter: [Array],
[hi-events] [2024-08-31 22:17:32]       transformRequest: [Array],
[hi-events] [2024-08-31 22:17:32]       transformResponse: [Array],
[hi-events] [2024-08-31 22:17:32]       timeout: 0,
[hi-events] [2024-08-31 22:17:32]       xsrfCookieName: 'XSRF-TOKEN',
[hi-events] [2024-08-31 22:17:32]       xsrfHeaderName: 'X-XSRF-TOKEN',
[hi-events] [2024-08-31 22:17:32]       maxContentLength: -1,
[hi-events] [2024-08-31 22:17:32]       maxBodyLength: -1,
[hi-events] [2024-08-31 22:17:32]       env: [Object],
[hi-events] [2024-08-31 22:17:32]       validateStatus: [Function: validateStatus],
[hi-events] [2024-08-31 22:17:32]       headers: [Object [AxiosHeaders]],
[hi-events] [2024-08-31 22:17:32]       method: 'get',
[hi-events] [2024-08-31 22:17:32]       url: 'events/2',
[hi-events] [2024-08-31 22:17:32]       baseURL: 'http://localhost:80/api/public',
[hi-events] [2024-08-31 22:17:32]       data: undefined
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     request: <ref *1> ClientRequest {
[hi-events] [2024-08-31 22:17:32]       _events: [Object: null prototype],
[hi-events] [2024-08-31 22:17:32]       _eventsCount: 7,
[hi-events] [2024-08-31 22:17:32]       _maxListeners: undefined,
[hi-events] [2024-08-31 22:17:32]       outputData: [],
[hi-events] [2024-08-31 22:17:32]       outputSize: 0,
[hi-events] [2024-08-31 22:17:32]       writable: true,
[hi-events] [2024-08-31 22:17:32]       destroyed: true,
[hi-events] [2024-08-31 22:17:32]       _last: true,
[hi-events] [2024-08-31 22:17:32]       chunkedEncoding: false,
[hi-events] [2024-08-31 22:17:32]       shouldKeepAlive: true,
[hi-events] [2024-08-31 22:17:32]       maxRequestsOnConnectionReached: false,
[hi-events] [2024-08-31 22:17:32]       _defaultKeepAlive: true,
[hi-events] [2024-08-31 22:17:32]       useChunkedEncodingByDefault: false,
[hi-events] [2024-08-31 22:17:32]       sendDate: false,
[hi-events] [2024-08-31 22:17:32]       _removedConnection: false,
[hi-events] [2024-08-31 22:17:32]       _removedContLen: false,
[hi-events] [2024-08-31 22:17:32]       _removedTE: false,
[hi-events] [2024-08-31 22:17:32]       strictContentLength: false,
[hi-events] [2024-08-31 22:17:32]       _contentLength: 0,
[hi-events] [2024-08-31 22:17:32]       _hasBody: true,
[hi-events] [2024-08-31 22:17:32]       _trailer: '',
[hi-events] [2024-08-31 22:17:32]       finished: true,
[hi-events] [2024-08-31 22:17:32]       _headerSent: true,
[hi-events] [2024-08-31 22:17:32]       _closed: true,
[hi-events] [2024-08-31 22:17:32]       socket: [Socket],
[hi-events] [2024-08-31 22:17:32]       _header: 'GET /api/public/events/2 HTTP/1.1\r\n' +
[hi-events] [2024-08-31 22:17:32]         'Accept: application/json, text/plain, */*\r\n' +
[hi-events] [2024-08-31 22:17:32]         'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3RpY2tldHMuZWJzLXNvY2lldHkuY29tL2F1dGgvbG9naW4iLCJpYXQiOjE3MjUxNDIxMTAsImV4cCI6MTcyNTc0NjkxMCwibmJmIjoxNzI1MTQyMTEwLCJqdGkiOiJZejlTcmtQY3gyR0cya1U3Iiwic3ViIjoiMSIsInBydiI6ImI1YjFhZjFhZWY1MWUyMmU1Y2JlMzk0YzM3NDU3MjJhYjgwYWQ2Y2MiLCJhY2NvdW50X2lkIjoxfQ.ahD1CYuHIh1sH8umow2YbTk04cf5KuxySVKPvdSs0dA\r\n' +
[hi-events] [2024-08-31 22:17:32]         'User-Agent: axios/1.7.5\r\n' +
[hi-events] [2024-08-31 22:17:32]         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
[hi-events] [2024-08-31 22:17:32]         'Host: localhost\r\n' +
[hi-events] [2024-08-31 22:17:32]         'Connection: keep-alive\r\n' +
[hi-events] [2024-08-31 22:17:32]         '\r\n',
[hi-events] [2024-08-31 22:17:32]       _keepAliveTimeout: 0,
[hi-events] [2024-08-31 22:17:32]       _onPendingData: [Function: nop],
[hi-events] [2024-08-31 22:17:32]       agent: [Agent],
[hi-events] [2024-08-31 22:17:32]       socketPath: undefined,
[hi-events] [2024-08-31 22:17:32]       method: 'GET',
[hi-events] [2024-08-31 22:17:32]       maxHeaderSize: undefined,
[hi-events] [2024-08-31 22:17:32]       insecureHTTPParser: undefined,
[hi-events] [2024-08-31 22:17:32]       joinDuplicateHeaders: undefined,
[hi-events] [2024-08-31 22:17:32]       path: '/api/public/events/2',
[hi-events] [2024-08-31 22:17:32]       _ended: true,
[hi-events] [2024-08-31 22:17:32]       res: [IncomingMessage],
[hi-events] [2024-08-31 22:17:32]       aborted: false,
[hi-events] [2024-08-31 22:17:32]       timeoutCb: null,
[hi-events] [2024-08-31 22:17:32]       upgradeOrConnect: false,
[hi-events] [2024-08-31 22:17:32]       parser: null,
[hi-events] [2024-08-31 22:17:32]       maxHeadersCount: null,
[hi-events] [2024-08-31 22:17:32]       reusedSocket: false,
[hi-events] [2024-08-31 22:17:32]       host: 'localhost',
[hi-events] [2024-08-31 22:17:32]       protocol: 'http:',
[hi-events] [2024-08-31 22:17:32]       _redirectable: [Writable],
[hi-events] [2024-08-31 22:17:32]       [Symbol(shapeMode)]: false,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kCapture)]: false,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kBytesWritten)]: 0,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kNeedDrain)]: false,
[hi-events] [2024-08-31 22:17:32]       [Symbol(corked)]: 0,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kOutHeaders)]: [Object: null prototype],
[hi-events] [2024-08-31 22:17:32]       [Symbol(errored)]: null,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kHighWaterMark)]: 16384,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kRejectNonStandardBodyWrites)]: false,
[hi-events] [2024-08-31 22:17:32]       [Symbol(kUniqueHeaders)]: null
[hi-events] [2024-08-31 22:17:32]     },
[hi-events] [2024-08-31 22:17:32]     data: {
[hi-events] [2024-08-31 22:17:32]       message: 'HiEvents\\DomainObjects\\TicketPriceDomainObject::setOffSaleReason(): Return value must be of type HiEvents\\DomainObjects\\TicketDomainObject, HiEvents\\DomainObjects\\TicketPriceDomainObject returned',
[hi-events] [2024-08-31 22:17:32]       exception: 'TypeError',
[hi-events] [2024-08-31 22:17:32]       file: '/app/backend/app/DomainObjects/TicketPriceDomainObject.php',
[hi-events] [2024-08-31 22:17:32]       line: 109,
[hi-events] [2024-08-31 22:17:32]       trace: [Array]
[hi-events] [2024-08-31 22:17:32]     }
[hi-events] [2024-08-31 22:17:32]   },
[hi-events] [2024-08-31 22:17:32]   status: 500
[hi-events] [2024-08-31 22:17:32] }
```


![image](https://github.com/user-attachments/assets/3d31f9b8-f78f-479c-b515-77071af51cef)
![image](https://github.com/user-attachments/assets/3c105e61-e125-4d44-b037-717adc25ec9a)

**Comment by daveearley** [comment]
Hi @kuhnfelix18052005,

I believe I've found the issue and a potential fix has been released. Please `Force rebuild and deploy` in DigitalOcean.

<img width="365" alt="Screenshot 2024-08-31 at 14 42 00" src="https://github.com/user-attachments/assets/ac216e2a-bf5b-4789-8762-c3d20ebe838f">

Let me know if that fixes the issue. 

Thanks

**Comment by kuhnfelix18052005** [comment]
Yes, thank you. It seems to have fixed the issue.

I'll let you know if there are any further problems...

**Comment by daveearley** [comment]
Great!
