### ISSUE TITLE
🐛 Promo codes with hidden tickets crashes front end

### ISSUE THREAD

**Issue by RealRunSpace** [HiEventsDev/Hi.Events#297]
> [!NOTE]
> Please stick to the template and provide as much detail as possible to help us diagnose and fix the issue.
> Low effort bug reports will be closed.

**Describe the bug**
When you hide a ticket to be only shown with a coupon code will generate an exception when using ANY coupon code in the whole page

**To Reproduce**
1. Create some ticket, one of them, hidden to be only seen by a coupon code
2. Create a exclusive coupon code for the hidden one and maybe a regular one just to test that this issue happens with any coupon if a product is hidden and only shown if a promo code is added to that item
3. 3. Apply any coupon, and boom, crash!

**Expected behavior**
Selected hidden ticket/item just appears after applying coupon. If it's not it's coupon, just not crash and apply the coupon

**Screenshots**
https://prnt.sc/vdAkU3yXYosj after clicking "apply promo code" button

**Logs**
`console.error @ index-DDaJcFkD.js:114
ld @ index-DDaJcFkD.js:41
Ty.o.componentDidCatch.n.callback @ index-DDaJcFkD.js:41
Bm @ index-DDaJcFkD.js:39
nh @ index-DDaJcFkD.js:41
Vy @ index-DDaJcFkD.js:41
jS @ index-DDaJcFkD.js:41
_S @ index-DDaJcFkD.js:41
Or @ index-DDaJcFkD.js:41
Uy @ index-DDaJcFkD.js:41
T @ index-DDaJcFkD.js:26
re @ index-DDaJcFkD.js:26
index-DDaJcFkD.js:114 React Router caught the following error during render Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ht (index-DDaJcFkD.js:39:17595)
    at ec (index-DDaJcFkD.js:39:17848)
    at Object.useState (index-DDaJcFkD.js:39:24658)
    at ne.useState (index-DDaJcFkD.js:10:6397)
    at i (use-disclosure-CGMtis-w.js:1:100)
    at index-Bf_VHn4e.js:27:19319
    at Array.map (<anonymous>)
    at e0 (index-Bf_VHn4e.js:27:19199)
    at qp (index-DDaJcFkD.js:39:17000)
    at ud (index-DDaJcFkD.js:41:3139) {componentStack: '\n    at e0 (https://hiddendomain.com/assets/ind….hiddendomain.com/assets/index-DDaJcFkD.js:119:387650)'}componentStack: "\n    at e0 (https://hiddendomain.com/assets/index-Bf_VHn4e.js:27:15630)\n    at div\n    at div\n    at div\n    at div\n    at div\n    at div\n    at yt (https://hiddendomain.com/assets/index-CdoTo8kO.js:1:11172)\n    at X (https://hiddendomain.com/assets/index-UVcnsgMa.js:1:1484)\n    at ik (https://hiddendomain.com/assets/index-DDaJcFkD.js:61:3752)\n    at ok (https://hiddendomain.com/assets/index-DDaJcFkD.js:61:2992)\n    at Lk (https://hiddendomain.com/assets/index-DDaJcFkD.js:70:5187)\n    at fk (https://hiddendomain.com/assets/index-DDaJcFkD.js:61:7245)\n    at Rk (https://hiddendomain.com/assets/index-DDaJcFkD.js:70:2389)\n    at PO (https://hiddendomain.com/assets/index-DDaJcFkD.js:119:40706)\n    at sx (https://hiddendomain.com/assets/index-DDaJcFkD.js:70:42435)\n    at hO (https://hiddendomain.com/assets/index-DDaJcFkD.js:119:38118)\n    at Wr (https://hiddendomain.com/assets/index-DDaJcFkD.js:119:51565)\n    at $0 (https://hiddendomain.com/assets/index-DDaJcFkD.js:111:23682)\n    at nw (https://hiddendomain.com/assets/index-DDaJcFkD.js:114:1685)\n    at dL (https://hiddendomain.com/assets/index-DDaJcFkD.js:119:387650)"[[Prototype]]: Object
console.error @ index-DDaJcFkD.js:114
componentDidCatch @ index-DDaJcFkD.js:61
Ty.o.componentDidCatch.n.callback @ index-DDaJcFkD.js:41
Bm @ index-DDaJcFkD.js:39
nh @ index-DDaJcFkD.js:41
Vy @ index-DDaJcFkD.js:41
jS @ index-DDaJcFkD.js:41
_S @ index-DDaJcFkD.js:41
Or @ index-DDaJcFkD.js:41
Uy @ index-DDaJcFkD.js:41
T @ index-DDaJcFkD.js:26
re @ index-DDaJcFkD.js:26
`

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Chrome
 - Version 131.0.6778.86 (Build oficial) (64 bits)

**Hi.Events Version and platform**
Please state the version of Hi.Events you are using and what platform it is hosted on. Local, Docker etc.
Docker all in one v0.8.0-beta.3

**Additional context**
After tinkering around, it looks like it's a front end error, but not completely sure because in the network tag it returns all the tickets properly

**Comment by RealRunSpace** [comment]
UPDATE: if you copy the URL of the coupon, the page will load properly, so it looks like if they is a hidden ticket and you apply a coupon, the backend will return info of the hidden ticket and the front end won't know what to do with the extra data, but if you already load the page with the coupon already places in (https://domain.com/event/1/event?promo_code=myAwesomePromoCOdeForHiddenTicket) will load the page properly, but if you remove the coupon after it was loaded, it will break the front end again

**Comment by daveearley** [comment]
Thanks for the report! This is a regression that was introduced with a recent feature release. I've a fix [ready to go](https://github.com/HiEventsDev/Hi.Events/pull/298). It will be released once it's been properly tested.

**Comment by RealRunSpace** [comment]
Great, thanks for the fast answer!!
