### ISSUE TITLE
🐛500 Error When Creating New Event Due to HTMLPurifier Cache Directory Not Writable

### ISSUE THREAD

**Issue by Wladefant** [HiEventsDev/Hi.Events#319]
### **Description**
When creating a new event, the backend throws a `500 Internal Server Error`. The issue is caused because the `HTMLPurifier` library cannot write to its cache directory (`DefinitionCache/Serializer`). 

---

### **Error Logs**
```plaintext
[2024-12-17 12:36:51] local.DEBUG: Stripe secret key is not set in the configuration file. Payment processing will not work.   
[2024-12-17 12:36:51] local.ERROR: Directory /app/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable.  
{"userId":1,"exception":"[object] (ErrorException(code: 0): Directory /app/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable.  
at /app/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php:295)
```

**Stack Trace**:
```
#0 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(512, 'Directory /app/...', '/app/vendor/ezy...', 295)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->{closure}(512, 'Directory /app/...', '/app/vendor/ezy...', 295)
#2 /app/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php(295): trigger_error('Directory /app/...', 512)
...
#11 /app/app/Services/Domain/Event/CreateEventService.php(91): HTMLPurifier->purify('<p>asdf</p>')
#14 /app/app/Http/Actions/Events/CreateEventAction.php(39): HiEvents\Services\Handlers\Event\CreateEventHandler->handle(Object(HiEvents\Services\Handlers\Event\DTO\CreateEventDTO))
...
#59 /app/public/index.php(51): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#60 {main}
```

---

### **Steps to Reproduce**
1. Go to the `/events` endpoint and attempt to create a new event.
2. The server returns a **500 Internal Server Error**.
3. Logs indicate the `DefinitionCache/Serializer` directory is not writable.

---

### **Expected Behavior**
The event should be created successfully without errors.

---

### **Actual Behavior**
The server throws a `500` error due to a write permission issue.

---

### **Root Cause**
1. **HTMLPurifier Cache Directory Issue**:  
   The `DefinitionCache/Serializer` directory does not have the correct write permissions, causing HTMLPurifier to fail when attempting to write cache data.

2. **Stripe Configuration**:  
   The Stripe secret key is missing in the `.env` file.

---

### **Environment**
- running in docker the Local development version without stripe or keys

**Comment by daveearley** [comment]
Hi @Wladefant,

How are you starting the container? The Dockerfile [handles this already](https://github.com/HiEventsDev/Hi.Events/blob/develop/Dockerfile.all-in-one#L34).

**Comment by Wladefant** [comment]
I am starting the docker/development start.sh Script and then this error comes

**Comment by daveearley** [comment]
That's odd, the `start-dev.sh` should be making that directory writable. When you run `start-dev.sh`, is the script executing successfully? 

As a workaround you can SSH into the container and run:

```bash
chmod -R 775 /app/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer
```

**Comment by daveearley** [comment]
Any update on this? Did you get it working?

**Comment by podzz** [comment]
Hi @daveearley 👋 Really appreciate your work here.

I was hitting the same issue while trying to use the latest from **v1.0.0-alpha** branch and spawning the stack docker.all.in.one install as described on the README.

I worked around this issue by updating the docker file to create an empty `/app/backend/bootstrap/cache` folder as it does not exist on that branch.

Full docker file:
```
FROM node:alpine AS node-frontend

WORKDIR /app/frontend

RUN apk add --no-cache yarn

COPY ./frontend/package.json ./frontend/yarn.lock ./

COPY ./frontend .

RUN yarn install && yarn build

FROM serversideup/php:beta-8.3.2-fpm-alpine

ENV PHP_OPCACHE_ENABLE=1

RUN install-php-extensions intl

RUN apk add --no-cache nodejs yarn nginx supervisor

COPY --from=node-frontend /app/frontend /app/frontend

COPY ./backend /app/backend
RUN chown -R www-data:www-data /app/backend \
    && find /app/backend -type d -exec chmod 755 {} \; \
    && find /app/backend -type f -exec chmod 644 {} \;

RUN mkdir -p /app/backend/bootstrap/cache <-- major change
RUN chmod -R 777 /app/backend/storage /app/backend/bootstrap/cache
RUN composer install --working-dir=/app/backend \
        --ignore-platform-reqs \
        --no-interaction \
        --no-dev \
        --optimize-autoloader \
        --prefer-dist \
    && chmod -R 777 /app/backend/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer

COPY ./docker/all-in-one/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/all-in-one/supervisor/supervisord.conf /etc/supervisord.conf

COPY ./docker/all-in-one/scripts/startup.sh /startup.sh
RUN dos2unix /startup.sh && chmod +x /startup.sh

EXPOSE 80

WORKDIR /app

CMD ["/startup.sh"]
```

**Comment by daveearley** [comment]
Fixed in https://github.com/HiEventsDev/Hi.Events/pull/282
